# -*- coding: utf-8 -*-
"""function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0dUP7pxQk3Q1nfm4lldgJYCnPDV28w2
"""

#1.write a function to add two numbers and return the result.
x=int(input("enter num x=:"))
y=int(input("enter num y=:"))
def add(x,y):
  return x+y
result=add (x,y)
print(result)

#2.write a function that checks whether a given number is even or odd.
num=int(input("enter num :"))
def even_odd(num):
    if num%2==0:
      print(num,"is even number")
    else:
      print(num,"is odd number")
even_odd(num)

#3.write a function to find the square of a given number.
def square(n):
  return n*n
result=square(8)
print(result)

#4.write a function that takes two numbers and returns the greater number.
def num(x,y):
  if x>y:
    print(x,"is greater")
  else:
    print(y,"is greater")
  return x>y
num(24,18)

#5.write a function to calculate the sum of first N natural numbers.
def sum_natural(n):
  total=0
  for i in range(1,n+1):
    total+=i
  return total
n=int(input("enter num:"))
result=(sum_natural(n))
print(result)

#6.write a function that takes a string and returns the number of characters in it.

char=input("enter the character :")
def len():
  len=0
  for i in char:
    len+=1
  return len
print("no of characters:",len())

#7.write a function to calculate simple interest using the formula SI=(P X T X R)/100.:
P=int(input("enter the principle :"))
T=int(input("enter the no of years :"))
R=int(input("enter the rate :"))
def simple_interest(P,T,R):
  return P*T*R/100
print(simple_interest(P,T,R))

#8.write a function that check given numb is +ve,or -ve.
n=int(input("enter num:"))
def integer(n):
  if n<0:
    print("-ve")
  elif n>0:
   print("+ve")
  else:
   print("zero")
integer(n)

#9.write a function to print the multiplication table of a given number.
num=int(input("enter num :"))
def table(num):
  for i in range (1,11):
   print(i,"x",num,"=",i*num)
table(num)

#10.write a function to calculate the area of a rectangle.
l=int(input("enter the length ="))
b=int(input("enter the breadth ="))
def rect_area(l,b):
  return l*b
result=rect_area(l,b)
print(result)

#11.write a function that uses a loop to print numbers from 1 to N
N=int(input("enter a num :"))
print("numbers from 1 to N",N)
def num():
 for i in range(1,N+1):
   print(i)
num()

#12.write a function that uses a loop to calculate the sum of all even numbers between 1 and N.
N=int(input("enter a num :"))
def num():
  sum=0
  for i in range(1,N+1):
   if i%2==0:
    sum+=i
  return sum
  print("sum of all even numbers:",N)
num()

#13.write a function that uses a loop to find the factorial of a given number.
num=int(input("enter num ;"))
def factorial():
  a=1
  b=1
  while a<=num:
   b=a*b
   a+=1
  return b
print("factorial of")
factorial()

#14.write a function that uses a loop to count how many digits are there in a given number.
n=int(input("enter num:"))
def counts(n):
  count=0
  while n>0:
   n=n//10
   count+=1
  return count
print("no of digits:")
counts(n)

#15.write a function that uses a loop to reverse a given number.
num=int(input("enter num"))
def reverse(num):
  rev_digits=0
  while num>0:
    digit=num%10
    rev_digits=rev_digits*10+digit
    num=num//10
  print("reverse of 8792 is",rev_digits)
reverse(num)

#16.write a function that uses conditional statements to check whether a given number is prime or not.
n=int(input("enter num:"))
def prime(n):
  c=0
  for i in range(1,n+1):
    if n%i==0:
      c+=1
  if c==2:
       print(n,"prime num")
  else:
       print(n,"not prime num")
prime(n)

#17.write a function that uses conditional statement to find the largest of three numbers.
a=int(input("enter first num:"))
b=int(input("enter second num:"))
c=int(input("enter thired num:"))
def largest_num(a,b,c):
  if a>=b and a>=c:
    return a
  elif b>=a and b>=c:
    return b
  else:
    return c
  print("largest num:")
largest_num(a,b,c)

#18.write a function that uses conditional statement to check whether a given year is a leap year or not.
year=int(input("enter year:"))
def leap_year(year):
    if year%400==0:
      print(year,"is a leap year")
    elif year%100==0:
      print(year,"not leap year")
    elif year%4==0:
      print(year,"is leap year")
    else:
      print("not leap year")
leap_year(year)

#19.write a function that uses both loop and conditional statemnts to count the number of vowels in a given string.

str=input("enter a char:")
def vowels(str):
  if str.lower()in "aeiou":
    print(str,"is a vowels")
  else:
    print(str,"not vowels")
vowels(str)

#20.write a function that uses both loop and conditionL statements to print only even numbers from a given list.

l=[10,11,12,13,14,15,16]
def even_num(l):
  for i in l:
    if i%2==0:
      print(i)
even_num(l)
